In [ ]:
import cv2
import numpy as np

In [65]:
image = cv2.imread('eren.jpg')
pioc = cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
print(image.shape)

(376, 800, 3)


In [13]:
print(image.dtype)

uint8


In [14]:
print(image.size)

902400


In [94]:
b,g,r = cv2.split(image)
p = cv2.merge([b,g,r])
cv2.imshow("e",p)
cv2.waitKey(0)

-1

In [27]:
print(b,g,r)

[[105  18  19 ...  55  55  58]
 [ 20  42  90 ...  65  66  66]
 [ 19  90 127 ...  64  63  62]
 ...
 [ 24  22  18 ...  78  64  78]
 [ 18  13   8 ...  65  79  62]
 [ 11   8   7 ...  46  87  72]] [[104  14  14 ...  43  43  46]
 [ 14  35  83 ...  49  50  50]
 [ 12  83 123 ...  45  44  43]
 ...
 [ 18  16  15 ...  69  55  67]
 [ 17  12   7 ...  56  69  50]
 [ 16  12   9 ...  40  77  60]] [[90  0  0 ...  9  9 12]
 [ 3 18 50 ... 12 14 14]
 [ 0 56 75 ...  7  6  5]
 ...
 [77 73 65 ... 89 75 87]
 [59 54 51 ... 76 86 68]
 [41 41 44 ... 59 94 78]]


In [95]:
zeros = np.zeros(b.shape,np.uint8)
b
cv2.imshow("Model Blue Image", cv2.merge([b,zeros,zeros])) 
  
# Displaying Green channel image 
# Green colour is highlighted the most 
cv2.imshow("Model Green Image", cv2.merge([zeros,g,zeros])) 
  
# Displaying Red channel image 
# Red colour is highlighted the most 
cv2.imshow("Model Red Image", cv2.merge([zeros,zeros,r]))
  
# Waits for user to press any key 
cv2.waitKey(0)


-1

In [96]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
cv2.imshow("g",gray)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [97]:

crop_img = image[0:222, 0:100]
cv2.imshow("cropped", crop_img)
cv2.waitKey(0)

-1

In [113]:
yuji = cv2.imread("choso.jpg")
cv2.imshow("e",yuji)
cv2.waitKey(0)

-1

In [111]:
a = cv2.imread("yuji.jpg")
cv2.imshow("e",a)
cv2.waitKey(0)

-1

In [88]:
yuji.shape

(450, 800, 3)

In [89]:
a.shape

(450, 800, 3)

In [114]:
pp = cv2.add(a,yuji)
cv2.imshow("cropped", pp)
cv2.waitKey(0)

-1

In [108]:
subtracted = cv2.subtract(a, yuji)
cv2.imshow("cropped", subtracted)
cv2.waitKey(0)

-1

In [115]:
d = cv2.bitwise_and(a,yuji)
cv2.imshow("cropped", d)
cv2.waitKey(0)

-1

In [104]:
f = cv2.bitwise_not(a,yuji)
cv2.imshow("cropped", f)
cv2.waitKey(0)

-1

In [123]:
image.shape

(376, 800, 3)

In [124]:
yuji.shape

(450, 800, 3)

In [125]:
ede = cv2.resize(yuji , (800,376))
ede.shape

(376, 800, 3)

In [128]:
fff = cv2.add(image,ede)
cv2.imshow("cropped", fff)
cv2.waitKey(0)

-1